In [15]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

df = pd.read_excel("Sample - Superstore.xls")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2020-138688,2020-06-12,2020-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [16]:
df.isnull().sum()

Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
Country/Region     0
City               0
State              0
Postal Code       11
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales              0
Quantity           0
Discount           0
Profit             0
dtype: int64

In [17]:
df["Postal Code"] = df["Postal Code"].fillna(0)

In [18]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State             0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [19]:
df["Postal Code"] = df["Postal Code"].astype(int)

In [20]:
df["Postal Code"].dtype

dtype('int64')

In [21]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("/", "_")
)

In [22]:
df.columns.tolist()

['row_id',
 'order_id',
 'order_date',
 'ship_date',
 'ship_mode',
 'customer_id',
 'customer_name',
 'segment',
 'country_region',
 'city',
 'state',
 'postal_code',
 'region',
 'product_id',
 'category',
 'sub-category',
 'product_name',
 'sales',
 'quantity',
 'discount',
 'profit']

In [23]:
df["order_year"] = df["order_date"].dt.year

df["order_month"] = df["order_date"].dt.month

df["order_month_name"] = df["order_date"].dt.month_name()

df["order_quarter"] = df["order_date"].dt.quarter

In [24]:
df[
    [
        "order_date",
        "order_year",
        "order_month",
        "order_month_name",
        "order_quarter"
    ]
].head()

  order_date  order_year  order_month order_month_name  order_quarter
0 2020-11-08        2020           11         November              4
1 2020-11-08        2020           11         November              4
2 2020-06-12        2020            6             June              2
3 2019-10-11        2019           10          October              4
4 2019-10-11        2019           10          October              4

In [25]:
df["shipping_days"] = (
    df["ship_date"] - df["order_date"]
).dt.days

In [26]:
df["shipping_days"].describe()

count    9994.000000
mean        3.958275
std         1.747598
min         0.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         7.000000
Name: shipping_days, dtype: float64

In [27]:
df["profit_margin_pct"] = (
    df["profit"] / df["sales"]
) * 100

In [28]:
df["profit_margin_pct"] = (
    df["profit_margin_pct"]
      .round(2)
)

In [29]:
df[
    [
        "sales",
        "profit",
        "profit_margin_pct"
    ]
].head()

      sales    profit  profit_margin_pct
0  261.9600   41.9136              16.00
1  731.9400  219.5820              30.00
2   14.6200    6.8714              47.00
3  957.5775 -383.0310             -40.00
4   22.3680    2.5164              11.25

In [30]:
loss_orders = (
    df["profit"] < 0
).sum()

print("Loss Making Orders:", loss_orders)

Loss Making Orders: 1871

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   row_id             9994 non-null   int64
 1   order_id           9994 non-null   object
 2   order_date         9994 non-null   datetime64[ns]
 3   ship_date          9994 non-null   datetime64[ns]
 4   ship_mode          9994 non-null   object
 5   customer_id        9994 non-null   object
 6   customer_name      9994 non-null   object
 7   segment            9994 non-null   object
 8   country_region     9994 non-null   object
 9   city               9994 non-null   object
 10  state              9994 non-null   object
 11  postal_code        9994 non-null   int64
 12  region             9994 non-null   object
 13  product_id         9994 non-null   object
 14  category           9994 non-null   object
 15  sub-category       9994 non-null   object
 16  product_name       9994 non-null   object
 17  sales              9994 non-null   float64
 18  quantity           9994 non-null   int64
 19  discount           9994 non-null   float64
 20  profit             9994 non-null   float64
 21  order_year         9994 non-null   int32
 22  order_month        9994 non-null   int32
 23  order_month_name   9994 non-null   object
 24  order_quarter      9994 non-null   int32
 25  shipping_days      9994 non-null   int64
 26  profit_margin_pct  9994 non-null   float64
dtypes: datetime64[ns](2), float64(4), int32(3), int64(4), object(14)
memory usage: 1.9+ MB

In [32]:
df.columns = df.columns.str.replace("-", "_")

In [33]:
df["shipping_days"].describe()

count    9994.000000
mean        3.958275
std         1.747598
min         0.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         7.000000
Name: shipping_days, dtype: float64

In [34]:
loss_orders = (df["profit"] < 0).sum()

print(loss_orders)

1871

In [36]:
df.shape

(9994, 27)

In [37]:
df["shipping_days"].describe()

count    9994.000000
mean        3.958275
std         1.747598
min         0.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         7.000000
Name: shipping_days, dtype: float64

In [38]:
loss_orders = (df["profit"] < 0).sum()
print(loss_orders)

1871

In [39]:
df.to_csv("superstore_cleaned.csv", index=False)